<?php

return [
    [
        'title' => 'Problema accesso utente',
        'description' => 'L\'utente non riesce ad accedere al proprio account.',
        'status' => 'assegnato',
        'operator_id' => 1,
        'category_id' => 1,
    ],
    [
        'title' => 'Errore nel carrello',
        'description' => 'Il carrello non mostra il totale corretto.',
        'status' => 'in_lavorazione',
        'operator_id' => 2,
        'category_id' => 2,
    ],
    [
        'title' => 'Problema di pagamento',
        'description' => 'Pagamento non andato a buon fine.',
        'status' => 'chiuso',
        'operator_id' => 3,
        'category_id' => 3,
    ],
    [
        'title' => 'Problema con la ricerca',
        'description' => 'La funzionalità di ricerca non restituisce i risultati corretti.',
        'status' => 'assegnato',
        'operator_id' => 4,
        'category_id' => 1,
    ],
    [
        'title' => 'Errore di visualizzazione',
        'description' => 'Le immagini non vengono caricate correttamente nella pagina.',
        'status' => 'in_lavorazione',
        'operator_id' => 5,
        'category_id' => 2,
    ],
    [
        'title' => 'Richiesta di supporto generale',
        'description' => 'L\'utente ha bisogno di assistenza su funzionalità generali.',
        'status' => 'chiuso',
        'operator_id' => 6,
        'category_id' => 3,
    ],
    [
        'title' => 'Errore nel login',
        'description' => 'Errore durante il tentativo di login.',
        'status' => 'assegnato',
        'operator_id' => 7,
        'category_id' => 1,
    ],
    [
        'title' => 'Problemi con l\'interfaccia utente',
        'description' => 'L\'interfaccia non è responsiva su dispositivi mobili.',
        'status' => 'in_lavorazione',
        'operator_id' => 8,
        'category_id' => 2,
    ],
    [
        'title' => 'Gestione password',
        'description' => 'Problemi con il recupero della password.',
        'status' => 'chiuso',
        'operator_id' => 9,
        'category_id' => 3,
    ],
    [
        'title' => 'Errori di configurazione',
        'description' => 'Errore nelle configurazioni del sistema.',
        'status' => 'assegnato',
        'operator_id' => 10,
        'category_id' => 1,
    ],
    [
        'title' => 'Bug nel sistema di ordini',
        'description' => 'Il sistema non registra correttamente gli ordini.',
        'status' => 'in_lavorazione',
        'operator_id' => 1,
        'category_id' => 2,
    ],
    [
        'title' => 'Problemi di sincronizzazione',
        'description' => 'La sincronizzazione dei dati non funziona correttamente.',
        'status' => 'chiuso',
        'operator_id' => 2,
        'category_id' => 3,
    ],
    [
        'title' => 'Errore di caricamento file',
        'description' => 'Il sistema non carica i file correttamente.',
        'status' => 'assegnato',
        'operator_id' => 3,
        'category_id' => 1,
    ],
    [
        'title' => 'Errore di accesso a pagine',
        'description' => 'Impossibile accedere a determinate pagine del sito.',
        'status' => 'in_lavorazione',
        'operator_id' => 4,
        'category_id' => 2,
    ],
];
